set(CMAKE_CXX_STANDARD 14 CACHE STRING "")

set( ENABLE_MPI ON CACHE BOOL "" FORCE )
set( ENABLE_FIND_MPI ON CACHE BOOL "" FORCE )

# HIP Options
set( ENABLE_HIP ON CACHE BOOL "" FORCE )

# suppress -Werror for now
set( ENABLE_WARNINGS_AS_ERRORS FALSE CACHE BOOL "" FORCE )

# GTEST
set(ENABLE_GTEST_DEATH_TESTS OFF CACHE BOOL "")
set(gtest_disable_pthreads ON CACHE BOOL "")

# disable most binaries and doc generation
set(ENABLE_TESTS OFF CACHE BOOL "" FORCE)
set(DISABLE_UNIT_TESTS ON CACHE BOOL "" FORCE)
set(ENABLE_EXAMPLES OFF CACHE BOOL "" FORCE)
set(ENABLE_BENCHMARKS OFF CACHE BOOL "" FORCE)
set(ENABLE_DOCS OFF CACHE BOOL "" FORCE)

# BLT trying to find MPI fails on cray with cce
set(ENABLE_FIND_MPI FALSE CACHE BOOL "")
