## CMake's compile command
# /usr/tce/packages/clang/clang-10.0.0/bin/clang++  -DsquareAll_EXPORTS -Iinclude -isystem /usr/gapps/GEOSX/thirdPartyLibs/2020-07-08/install-quartz-clang@10.0.0-release/raja/include -isystem /usr/tce/packages/mvapich2/mvapich2-2.3-clang-10.0.0/include -isystem /usr/gapps/GEOSX/thirdPartyLibs/2020-07-08/install-quartz-clang@10.0.0-release/caliper/include -isystem /usr/gapps/GEOSX/thirdPartyLibs/2020-07-08/install-quartz-clang@10.0.0-release/chai/include -Wall -Wextra -Werror -fopenmp=libomp  -Wall -Wextra -Wpedantic -pedantic-errors -Wshadow -Wfloat-equal -Wcast-align -Wcast-qual -fcolor-diagnostics  -g -fstandalone-debug  -fPIC   -fopenmp=libomp -std=c++14 -fPIC -c /usr/WS2/corbett5/LvArray/src/jitti/templateSource.cpp -o /usr/WS2/corbett5/LvArray/build-quartz-clang@10.0.0-debug/lib/jitti/squareAll.o -D JITTI_TEMPLATE_HEADER_FILE='"/usr/WS2/corbett5/LvArray/unitTests/jitti/squareAll.hpp"' -D JITTI_TEMPLATE_FUNCTION=squareAll -D JITTI_TEMPLATE_PARAMS='RAJA::loop_exec'

## My compile command
/usr/tce/packages/clang/clang-10.0.0/bin/clang++  -DsquareAll_EXPORTS -Iinclude -isystem /usr/gapps/GEOSX/thirdPartyLibs/2020-07-08/install-quartz-clang@10.0.0-release/raja/include -isystem /usr/tce/packages/mvapich2/mvapich2-2.3-clang-10.0.0/include -isystem /usr/gapps/GEOSX/thirdPartyLibs/2020-07-08/install-quartz-clang@10.0.0-release/caliper/include -isystem /usr/gapps/GEOSX/thirdPartyLibs/2020-07-08/install-quartz-clang@10.0.0-release/chai/include -Wall -Wextra -Werror -fopenmp=libomp  -Wall -Wextra -Wpedantic -pedantic-errors -Wshadow -Wfloat-equal -Wcast-align -Wcast-qual -fcolor-diagnostics  -g -fstandalone-debug  -fPIC   -fopenmp=libomp -std=c++14 -fPIC -c /usr/WS2/corbett5/LvArray/src/jitti/templateSource.cpp -o /usr/WS2/corbett5/LvArray/build-quartz-clang@10.0.0-debug/lib/jitti/squareAll.o -D JITTI_TEMPLATE_HEADER_FILE='"/usr/WS2/corbett5/LvArray/unitTests/jitti/squareAll.hpp"' -D JITTI_TEMPLATE_FUNCTION=squareAll -D JITTI_TEMPLATE_PARAMS='RAJA::loop_exec'

## CMake's link command
# /usr/tce/packages/clang/clang-10.0.0/bin/clang++ /usr/WS2/corbett5/LvArray/build-quartz-clang@10.0.0-debug/lib/jitti/squareAll.o lib/liblvarray.a lib/libjitti.a /usr/gapps/GEOSX/thirdPartyLibs/2020-07-08/install-quartz-clang@10.0.0-release/raja/lib/libRAJA.a -ldl -shared -o /usr/WS2/corbett5/LvArray/build-quartz-clang@10.0.0-debug/lib/jitti/libsquareAll.so

## My link command
/usr/tce/packages/clang/clang-10.0.0/bin/clang++ /usr/WS2/corbett5/LvArray/build-quartz-clang@10.0.0-debug/lib/jitti/squareAll.o -L/usr/WS2/corbett5/LvArray/build-quartz-clang@10.0.0-debug/lib -llvarray -ljitti /usr/gapps/GEOSX/thirdPartyLibs/2020-07-08/install-quartz-clang@10.0.0-release/raja/lib/libRAJA.a -fPIC -shared -o /usr/WS2/corbett5/LvArray/build-quartz-clang@10.0.0-debug/lib/jitti/libsquareAll.so
