rm lib/jitti/libsquareAll.so

set LIBS=/usr/gapps/GEOSX/thirdPartyLibs/2020-07-08/install-lassen-clang@upstream-release/raja/lib/libRAJA.a lib/libjitti.a lib/liblvarray.a

# /usr/tce/packages/cuda/cuda-10.1.243/bin/nvcc -ccbin=/usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-clang-upstream-2019.03.26/bin/mpicxx -restrict -arch sm_70 --expt-extended-lambda -Werror cross-execution-space-call,reorder,deprecated-declarations -g -G -O0 -Xcompiler -O0 -Xcompiler=-fPIC -Iinclude -isystem=/usr/tce/packages/cuda/cuda-10.1.243/include -isystem=/usr/gapps/GEOSX/thirdPartyLibs/2020-07-08/install-lassen-clang@upstream-release/raja/include -Xcompiler=-fopenmp=libomp -std=c++14 -x cu -c ../unitTests/jitti/squareAll.cpp -o unitTests/jitti/CMakeFiles/squareAllDummy.dir/squareAll.cpp.o

# /usr/tce/packages/clang/clang-upstream-2019.03.26/bin/clang++ -fPIC -Wall -Wextra   -Werror  -fopenmp=libomp  -Wall -Wextra -Wpedantic -pedantic-errors -Wshadow -Wfloat-equal -Wcast-align -Wcast-qual   -fcolor-diagnostics  -O0 -g -fstandalone-debug -pthread -L/usr/tce/packages/cuda/cuda-10.1.243/lib64 -fopenmp=libomp -shared -Wl,-soname,libsquareAllDummy.so -o lib/libsquareAllDummy.so unitTests/jitti/CMakeFiles/squareAllDummy.dir/squareAll.cpp.o -L/usr/tce/packages/cuda/cuda-10.1.243/nvidia/targets/ppc64le-linux/lib/stubs  -L/usr/tce/packages/cuda/cuda-10.1.243/nvidia/targets/ppc64le-linux/lib /usr/tce/packages/cuda/cuda-10.1.243/lib64/libcudart_static.a -pthread -ldl /usr/lib64/librt.so $LIBS -lpthread /usr/lib64/librt.so -ldl -lcudadevrt -lcudart_static -lrt -lpthread -ldl -lpthread

/usr/tce/packages/cuda/cuda-10.1.243/bin/nvcc -ccbin=/usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-clang-upstream-2019.03.26/bin/mpicxx -restrict -arch sm_70 --expt-extended-lambda -Werror cross-execution-space-call,reorder,deprecated-declarations -g -G -O0 -Xcompiler -O0 -Xcompiler=-fPIC -Iinclude -isystem=/usr/tce/packages/cuda/cuda-10.1.243/include -isystem=/usr/gapps/GEOSX/thirdPartyLibs/2020-07-08/install-lassen-clang@upstream-release/raja/include -Xcompiler=-fopenmp=libomp -std=c++14 -x cu -c ../src/jitti/templateSource.cpp -o unitTests/jitti/CMakeFiles/squareAllDummy.dir/templateSource.cpp.o -D JITTI_TEMPLATE_HEADER_FILE='"/usr/WS2/corbett5/LvArray/unitTests/jitti/squareAll.hpp"' -D JITTI_TEMPLATE_FUNCTION=squareAll -D JITTI_TEMPLATE_PARAMS='RAJA::loop_exec'

/usr/tce/packages/clang/clang-upstream-2019.03.26/bin/clang++ -fPIC -Wall -Wextra   -Werror  -fopenmp=libomp  -Wall -Wextra -Wpedantic -pedantic-errors -Wshadow -Wfloat-equal -Wcast-align -Wcast-qual   -fcolor-diagnostics  -O0 -g -fstandalone-debug -pthread -L/usr/tce/packages/cuda/cuda-10.1.243/lib64 -fopenmp=libomp -shared -Wl,-soname,libsquareAll.so -o lib/jitti/libsquareAll.so unitTests/jitti/CMakeFiles/squareAllDummy.dir/templateSource.cpp.o -L/usr/tce/packages/cuda/cuda-10.1.243/nvidia/targets/ppc64le-linux/lib/stubs  -L/usr/tce/packages/cuda/cuda-10.1.243/nvidia/targets/ppc64le-linux/lib /usr/tce/packages/cuda/cuda-10.1.243/lib64/libcudart_static.a -pthread -ldl /usr/lib64/librt.so $LIBS -lpthread /usr/lib64/librt.so -ldl -lcudadevrt -lcudart_static -lrt -lpthread -ldl -lpthread


ls lib/jitti/libsquareAll.so
